name: API linting & tests

on: [pull_request, workflow_dispatch]

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    services:
      mongo:
        image: mongo:3.6.3
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: nrpti-dev
        options: >-
          --health-cmd "mongo --quiet --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.filter.outputs.api == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        if: steps.filter.outputs.api == 'true'
        run: |
          cd api
          npm install
        env:
          CI: true
      - name: lint
        if: steps.filter.outputs.api == 'true'
        run: |
          cd api
          npx eslint .
          npx prettier './src/**/*.js' --check --log-level warn

      - name: Install MongoDB driver
        if: steps.filter.outputs.api == 'true'
        run: npm install mongodb@3.6
      - name: Setup Mongo DB
        if: steps.filter.outputs.api == 'true'
        run: node ./mongoSeed/mongo-seed-CI.js
        env:
          MONGO_URI: mongodb://localhost:27017/nrpti-dev
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      - name: test
        if: steps.filter.outputs.api == 'true'
        run: |
          cd api
          npm run test
        env:
          MONGO_URI: mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD}}@localhost:27017/nrpti-dev
          CI: true
