name: Front-End linting & tests

on: [pull_request, workflow_dispatch]
concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
      id: filter
      with:
        filters: |
          frontend:
            - 'angular/**'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      if: steps.filter.outputs.frontend == 'true'
      run: |
        cd angular
        npm install
      env:
        CI: true
    - name: build, and test
      if: steps.filter.outputs.frontend == 'true'
      run: |
        cd angular
        npx ng build global
        npx ng run admin-nrpti:test-ci
        npx ng common:test
        npx ng global:test
        npx ng public-nrced:test
      env:
        CI: true
